<?php

use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert ([
            ['nome'=>'Mario',
             'cognome'=>'Rossi',
             'username'=>'MarioRossi',
             'password'=>Hash::make('mario_rossi'),
             'email'=>'mariorossi@prova.com',
             'role'=>'user',
             'residenza'=>'Milano',
             'dataNascita'=>'1958-01-10',
             'occupazione'=>'Insegnante'],
            ['nome'=>'Luca',
             'cognome'=>'Biachi',
             'username'=>'LucaBianchi',
             'password'=>Hash::make('luca_bianchi'),
             'email'=>'lucabianchi@prova.com',
             'role'=>'user',
             'residenza'=>'Palermo',
             'dataNascita'=>'1987-03-26',
             'occupazione'=>'Metalmeccanico'],
            ['nome'=>'Antonio',
             'cognome'=>'Verdi',
             'username'=>'AntonioVerdi',
             'password'=>Hash::make('antonio_verdi'),
             'email'=>'antonioverdi@prova.com',
             'role'=>'user',
             'residenza'=>'Palo Alto',
             'dataNascita'=>'2000-10-12',
             'occupazione'=>'Militare'],
            ['nome'=>'Federica',
             'cognome'=>'Perlati',
             'username'=>'FedericaPerlati',
             'password'=>Hash::make('federica_perlati'),
             'email'=>'federicaperlati@prova.com',
             'role'=>'user',
             'residenza'=>'Brescia',
             'dataNascita'=>'1976-08-29',
             'occupazione'=>'Operaia'],
            ['nome'=>'Francesca',
             'cognome'=>'Pedretti',
             'username'=>'FrancescaPedretti',
             'password'=>Hash::make('francesca_pedretti'),
             'email'=>'francescapedretti@prova.com',
             'role'=>'user',
             'residenza'=>'Brindisi',
             'dataNascita'=>'1991-06-14',
             'occupazione'=>'Dirigente'],
            ['nome'=>'Paolo',
             'cognome'=>'Caneva',
             'username'=>'PaoloCaneva',
             'password'=>Hash::make('paolo_caneva'),
             'email'=>'paolocaneva@prova.com',
             'role'=>'user',
             'residenza'=>'Ancona',
             'dataNascita'=>'1983-05-02',
             'occupazione'=>'Commercialista'],
            ['nome'=>'Alessandro',
             'cognome'=>'Piacentini',
             'username'=>'AlessandroPiacentini',
             'password'=>Hash::make('alessandro_piacentini'),
             'email'=>'alessandropiacentini@prova.com',
             'role'=>'user',
             'residenza'=>'Trieste',
             'dataNascita'=>'1979-11-16',
             'occupazione'=>'Operaio'],
            ['nome'=>'Lucia',
             'cognome'=>'Moccia',
             'username'=>'LuciaMoccia',
             'password'=>Hash::make('lucia_moccia'),
             'email'=>'luciamoccia@prova.com',
             'role'=>'user',
             'residenza'=>'Bergamo',
             'dataNascita'=>'1984-06-18',
             'occupazione'=>'SocialMedia Manager'],
             
            //utenti User, Staff, Admin
            ['nome'=>'User',
             'cognome'=>'User',
             'username'=>'useruser',
             'password'=>Hash::make('pQoQBc8A'),
             'email'=>'useruser@tweb.com',
             'role'=>'user',
             'residenza'=>'Pavia',
             'dataNascita'=>'1993-02-19',
             'occupazione'=>'User'],
            ['nome'=>'Staff',
             'cognome'=>'Staff',
             'username'=>'staffstaff',
             'password'=>Hash::make('pQoQBc8A'),
             'email'=>'staffstaff@tweb.com',
             'role'=>'staff',
             'residenza'=>'Bologna',
             'dataNascita'=>'1984-04-21',
             'occupazione'=>'Staff'],
            ['nome'=>'Admin',
             'cognome'=>'Admin',
             'username'=>'adminadmin',
             'password'=>Hash::make('pQoQBc8A'),
             'email'=>'adminadmin@tweb.com',
             'role'=>'admin',
             'residenza'=>'Lugano',
             'dataNascita'=>'1989-10-23',
             'occupazione'=>'Admin'],
        ]);
    }
}
