<?php

use Illuminate\Database\Seeder;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('utente')->insert ([
            ['nome'=>'Mario',
             'cognome'=>'Rossi',
             'username'=>'MarioRossi',
             'password'=>'mario_rossi',
             'email'=>'mariorossi@prova.com',
             'ruolo'=>'user',
             'residenza'=>'Milano',
             'dataNascita'=>'10/01/1958',
             'occupazione'=>'Insegnante'],
            ['nome'=>'Luca',
             'cognome'=>'Biachi',
             'username'=>'LucaBianchi',
             'password'=>'luca_bianchi',
             'email'=>'lucabianchi@prova.com',
             'ruolo'=>'user',
             'residenza'=>'Palermo',
             'dataNascita'=>'26/03/1987',
             'occupazione'=>'Metalmeccanico'],
            ['nome'=>'Antonio',
             'cognome'=>'Verdi',
             'username'=>'AntonioVerdi',
             'password'=>'antonio_verdi',
             'email'=>'antonioverdi@prova.com',
             'ruolo'=>'user',
             'residenza'=>'Palo Alto',
             'dataNascita'=>'12/10/2000',
             'occupazione'=>'Militare'],
            ['nome'=>'Federica',
             'cognome'=>'Perlati',
             'username'=>'FedericaPerlati',
             'password'=>'federica_perlati',
             'email'=>'federicaperlati@prova.com',
             'ruolo'=>'user',
             'residenza'=>'Brescia',
             'dataNascita'=>'29/08/1976',
             'occupazione'=>'Operaia'],
            ['nome'=>'Francesca',
             'cognome'=>'Pedretti',
             'username'=>'FrancescaPedretti',
             'password'=>'francesca_pedretti',
             'email'=>'francescapedretti@prova.com',
             'ruolo'=>'user',
             'residenza'=>'Brindisi',
             'dataNascita'=>'14/06/1991',
             'occupazione'=>'Dirigente'],
            ['nome'=>'Paolo',
             'cognome'=>'Caneva',
             'username'=>'PaoloCaneva',
             'password'=>'paolo_caneva',
             'email'=>'paolocaneva@prova.com',
             'ruolo'=>'user',
             'residenza'=>'Ancona',
             'dataNascita'=>'02/05/1983',
             'occupazione'=>'Commercialista'],
            ['nome'=>'Alessandro',
             'cognome'=>'Piacentini',
             'username'=>'AlessandroPiacentini',
             'password'=>'alessandro_piacentini',
             'email'=>'alessandropiacentini@prova.com',
             'ruolo'=>'user',
             'residenza'=>'Trieste',
             'dataNascita'=>'16/11/1979',
             'occupazione'=>'Operaio'],
            ['nome'=>'Lucia',
             'cognome'=>'Moccia',
             'username'=>'LuciaMoccia',
             'password'=>'lucia_moccia',
             'email'=>'luciamoccia@prova.com',
             'ruolo'=>'user',
             'residenza'=>'Bergamo',
             'dataNascita'=>'18/06/1984',
             'occupazione'=>'SocialMediaManager'],
             
            //utenti User, Staff, Admin
            ['nome'=>'User',
             'cognome'=>'User',
             'username'=>'useruser',
             'password'=>'useruser',
             'email'=>'useruser@tweb.com',
             'ruolo'=>'user',
             'residenza'=>'Pavia',
             'dataNascita'=>'19/02/1993',
             'occupazione'=>'User'],
            ['nome'=>'Staff',
             'cognome'=>'Staff',
             'username'=>'staffstaff',
             'password'=>'staffstaff',
             'email'=>'staffstaff@tweb.com',
             'ruolo'=>'staff',
             'residenza'=>'Bologna',
             'dataNascita'=>'21/04/1984',
             'occupazione'=>'Staff'],
            ['nome'=>'Admin',
             'cognome'=>'Admin',
             'username'=>'adminadmin',
             'password'=>'adminadmin',
             'email'=>'adminadmin@tweb.com',
             'ruolo'=>'admin',
             'residenza'=>'Lugano',
             'dataNascita'=>'23/10/1989',
             'occupazione'=>'Admin'],
        ]);
    }
}
