<?php

use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //User, Staff e Admin
        DB::table('users')->insert ([ 
            ['name'=>'User',
             'surname'=>'User',
             'email'=>'useruser@tweb.com',
             'username'=>'useruser',
             'password'=>Hash::make('pQoQBc8A'),
             'role'=>'user',
             'residence'=>'Pavia',
             'birthday'=>'1993-02-19',
             'job'=>'Operaio',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")],
            ['name'=>'Staff',
             'surname'=>'Staff',
             'email'=>'staffstaff@tweb.com',
             'username'=>'staffstaff',
             'password'=>Hash::make('pQoQBc8A'),
             'role'=>'staff',
             'residence'=>'Bologna',
             'birthday'=>'1984-04-21',
             'job'=>'Architetto',
            'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            ['name'=>'Admin',
             'surname'=>'Admin',
             'email'=>'adminadmin@tweb.com',
             'username'=>'adminadmin',
             'password'=>Hash::make('pQoQBc8A'),
             'role'=>'admin',
             'residence'=>'Lugano',
             'birthday'=>'1989-10-23',
             'job'=>'Insegnante',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            ['name'=>'UserProva1',
             'surname'=>'UserProva1',
             'email'=>'userprova1@tweb.com',
             'username'=>'userprova1',
             'password'=>Hash::make('userprova1'),
             'role'=>'user',
             'residence'=>'Ancona',
             'birthday'=>'1993-02-19',
             'job'=>'Operaio',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")],
            ['name'=>'UserProva2',
             'surname'=>'UserProva2',
             'email'=>'userprova2@tweb.com',
             'username'=>'userprova2',
             'password'=>Hash::make('userprova2'),
             'role'=>'user',
             'residence'=>'Pavia',
             'birthday'=>'1993-02-19',
             'job'=>'Operaio',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")],
            ['name'=>'UserProva3',
             'surname'=>'UserProva3',
             'email'=>'userprova3@tweb.com',
             'username'=>'userprova3',
             'password'=>Hash::make('userprova3'),
             'role'=>'user',
             'residence'=>'Pavia',
             'birthday'=>'1993-02-19',
             'job'=>'Operaio',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")],
            ['name'=>'StaffProva1',
             'surname'=>'StaffProva1',
             'email'=>'staffprova1@tweb.com',
             'username'=>'staffprova1',
             'password'=>Hash::make('staffprova1'),
             'role'=>'staff',
             'residence'=>'Bologna',
             'birthday'=>'1984-04-21',
             'job'=>'Architetto',
            'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            ['name'=>'StaffProva2',
             'surname'=>'StaffProva2',
             'email'=>'staffprova2@tweb.com',
             'username'=>'staffprova2',
             'password'=>Hash::make('staffprova2'),
             'role'=>'staff',
             'residence'=>'Bologna',
             'birthday'=>'1984-04-21',
             'job'=>'Architetto',
            'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            ['name'=>'StaffProva3',
             'surname'=>'StaffProva3',
             'email'=>'staffprova3@tweb.com',
             'username'=>'staffprova3',
             'password'=>Hash::make('staffprova3'),
             'role'=>'staff',
             'residence'=>'Bologna',
             'birthday'=>'1984-04-21',
             'job'=>'Architetto',
            'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],

        ]);
    }
}
